services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ADT\BackgroundQueue\Console\ReloadConsumersCommand:
        tags:
            - { name: 'console.command' }
            - { name: 'background-queue.command'}
    ADT\BackgroundQueue\Console\ConsumeCommand:
        tags:
            - { name: 'console.command' }