services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ADT\BackgroundQueue\BackgroundQueue:
        lazy: true
        arguments:
            $config: '%background_queue%'

    ADT\BackgroundQueueSymfony\Broker\Consumer:
        lazy: true

    ADT\BackgroundQueueSymfony\Broker\Producer:
        lazy: true
        arguments:
            $container: '@service_container'

    ADT\BackgroundQueue\Console\ClearFinishedCommand:
        tags:
            - { name: 'console.command' }
    ADT\BackgroundQueue\Console\ProcessCommand:
        tags:
            - { name: 'console.command' }
    ADT\BackgroundQueue\Console\ReloadConsumersCommand:
        tags:
            - { name: 'console.command' }
    ADT\BackgroundQueue\Console\UpdateSchemaCommand:
        tags:
            - { name: 'console.command' }